# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0004_auto_20160325_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(blank=True, choices=[(b'en', b'English')], default='', help_text='Render template in alternative language', max_length=12),
        ),
    ]
